import { Request, Response } from "express";
import { getAllFood, getFoodById } from "../../services/food/food.service";
import { SuccessResponse } from "../../utils/Response";
import { BadRequest } from "../../errors";

export const getAllFoodController = async (req: Request, res: Response) => {
    const { page, limit, search } = req.query;
    const food = await getAllFood({
        page:   page   ? Number(page)   : undefined,
        limit:  limit  ? Number(limit)  : undefined,
        search: search as string,
    });
    return SuccessResponse(res, food, 200);
};

export const getFoodByIdController = async (req: Request, res: Response) => {
    const { id } = req.params;
    if (!id) {
        throw new BadRequest("Id is required");
    }
    const food = await getFoodById(id as string);
    return SuccessResponse(res, food, 200);
};

//! Created by Antigravity: Controller to create custom food generated by AI coach
export const createCustomFoodController = async (req: Request, res: Response) => {
    const { name, calories, protein, carbs, fats } = req.body;

    if (!name) {
        throw new BadRequest("Food name is required");
    }

    const { createOrGetCustomFood } = await import("../../services/food/food.service");
    const newFood = await createOrGetCustomFood({
        name,
        calories: Number(calories) || 0,
        protein: Number(protein) || 0,
        carbs: Number(carbs) || 0,
        fats: Number(fats) || 0,
    });

    return SuccessResponse(res, newFood, 201);
};
