import { Request, Response } from "express";
import {
    getAllFood,
    getFoodById,
    getAllFoodDb,
    getFoodDbById,
    createFood,
    updateFood,
    deleteFood,
} from "../../services/food/food.service";
import { SuccessResponse } from "../../utils/Response";
import { BadRequest } from "../../errors";

/**
 * Existing external AI API helper to get food list
 */
export const getAllFoodController = async (req: Request, res: Response) => {
    const { page, limit, search } = req.query;
    const food = await getAllFood({
        page:   page   ? Number(page)   : undefined,
        limit:  limit  ? Number(limit)  : undefined,
        search: search as string,
    });
    return SuccessResponse(res, food, 200);
};

/**
 * Existing external AI API helper to get food by ID
 */
export const getFoodByIdController = async (req: Request, res: Response) => {
    const { id } = req.params;
    if (!id) {
        throw new BadRequest("Id is required");
    }
    const food = await getFoodById(id as string);
    return SuccessResponse(res, food, 200);
};

/**
 * Existing controller to create custom food generated by AI coach
 */
export const createCustomFoodController = async (req: Request, res: Response) => {
    const { name, calories, protein, carbs, fats } = req.body;

    if (!name) {
        throw new BadRequest("Food name is required");
    }

    const { createOrGetCustomFood } = await import("../../services/food/food.service");
    const newFood = await createOrGetCustomFood({
        name,
        calories: Number(calories) || 0,
        protein: Number(protein) || 0,
        carbs: Number(carbs) || 0,
        fats: Number(fats) || 0,
    });

    return SuccessResponse(res, newFood, 201);
};

/* ==========================================
   ADMINISTRATIVE LOCAL DB CRUD CONTROLLERS
   ========================================== */

/**
 * Controller to fetch all food items from local database
 */
export const getAllFoodDbController = async (req: Request, res: Response) => {
    const page = req.query.page ? Number(req.query.page) : 1;
    const limit = req.query.limit ? Number(req.query.limit) : 10;
    const search = req.query.search as string | undefined;

    const result = await getAllFoodDb({ page, limit, search });
    return SuccessResponse(res, result, 200);
};

/**
 * Controller to fetch a single local database food item by ID
 */
export const getFoodDbByIdController = async (req: Request, res: Response) => {
    const { id } = req.params;
    if (!id) {
        throw new BadRequest("Food item ID is required");
    }

    const result = await getFoodDbById(Number(id));
    return SuccessResponse(res, result, 200);
};

/**
 * Controller to create a new food item in the local database
 */
export const createFoodController = async (req: Request, res: Response) => {
    const { class_name } = req.body;
    if (!class_name) {
        throw new BadRequest("Food class name is required");
    }

    const result = await createFood(req.body);
    return SuccessResponse(res, result, 201);
};

/**
 * Controller to update an existing food item in the local database
 */
export const updateFoodController = async (req: Request, res: Response) => {
    const { id } = req.params;
    if (!id) {
        throw new BadRequest("Food item ID is required");
    }

    const result = await updateFood(Number(id), req.body);
    return SuccessResponse(res, result, 200);
};

/**
 * Controller to delete a food item and clean references
 */
export const deleteFoodController = async (req: Request, res: Response) => {
    const { id } = req.params;
    if (!id) {
        throw new BadRequest("Food item ID is required");
    }

    const result = await deleteFood(Number(id));
    return SuccessResponse(res, result, 200);
};
