import { apiRequest } from "../api/apiRequest.service";
import { aiBaseurl } from "../../constants/api.constants";
import { db } from "../../db/connection";
import { foodItems } from "../../models/food_items";
import { recipeIngredients } from "../../models/recipe_ingredients";
import { mealPlanItems } from "../../models/meal_plan_items";
import { dailyLogs } from "../../models/daily_logs";
import { eq, like, desc, count } from "drizzle-orm";
import { NotFound, BadRequest } from "../../errors";

/**
 * Existing external AI API helper to get food list
 */
export const getAllFood = async (params: {
    page?:   number;
    limit?:  number;
    search?: string;
}) => {
    const query = new URLSearchParams();
    if (params.page)   query.append("page",   params.page.toString());
    if (params.limit)  query.append("limit",  params.limit.toString());
    if (params.search) query.append("search", params.search);

    const queryString = query.size ? `?${query.toString()}` : "";
    return apiRequest(`${aiBaseurl}/food/${queryString}`, "GET", {});
};

/**
 * Existing external AI API helper to get food by ID
 */
export const getFoodById = async (id: string) => {
    const response = await apiRequest(`${aiBaseurl}/food/${id}`, "GET", {});
    return response;
};

/**
 * Existing service to create or get a custom food item generated by the AI
 */
export const createOrGetCustomFood = async (data: {
    name: string;
    calories: number;
    protein: number;
    carbs: number;
    fats: number;
}) => {
    const existingFood = await db.query.foodItems.findFirst({
        where: eq(foodItems.class_name, data.name)
    });

    if (existingFood) {
        return existingFood;
    }

    await db.insert(foodItems).values({
        class_name: data.name,
        cals_per_100g: data.calories,
        protein_per_100g: data.protein,
        carbs_per_100g: data.carbs,
        fats_per_100g: data.fats,
        source: 'UserCreated',
        isVerified: false,
    });

    const newFood = await db.query.foodItems.findFirst({
        where: eq(foodItems.class_name, data.name)
    });

    return newFood;
};

/* ==========================================
   ADMINISTRATIVE LOCAL DB CRUD OPERATIONS
   ========================================== */

/**
 * Get all food items from local database with pagination and search
 */
export const getAllFoodDb = async ({
    page = 1,
    limit = 10,
    search,
}: {
    page?: number;
    limit?: number;
    search?: string;
}) => {
    const skip = (page - 1) * limit;

    const whereClause = search
        ? like(foodItems.class_name, `%${search}%`)
        : undefined;

    const totalResult = await db
        .select({ value: count() })
        .from(foodItems)
        .where(whereClause);

    const total = totalResult[0]?.value || 0;

    const foodList = await db.query.foodItems.findMany({
        where: whereClause,
        limit: limit,
        offset: skip,
        orderBy: [desc(foodItems.id)],
    });

    return {
        foodItems: foodList,
        total,
        page,
        limit,
    };
};

/**
 * Get single food item from local database by ID
 */
export const getFoodDbById = async (id: number) => {
    const food = await db.query.foodItems.findFirst({
        where: eq(foodItems.id, id),
    });

    if (!food) {
        throw new NotFound(`Food item with ID ${id} not found`);
    }

    return food;
};

/**
 * Create a new food item in the local database
 */
export const createFood = async (data: any) => {
    const { class_name, ...extraData } = data;

    if (!class_name) {
        throw new BadRequest("Food class name is required");
    }

    const existing = await db.query.foodItems.findFirst({
        where: eq(foodItems.class_name, class_name),
    });

    if (existing) {
        throw new BadRequest("Food item with this name already exists");
    }

    await db.insert(foodItems).values({
        class_name,
        ...extraData,
    });

    const newFood = await db.query.foodItems.findFirst({
        where: eq(foodItems.class_name, class_name),
    });

    if (!newFood) {
        throw new BadRequest("Failed to retrieve newly created food item");
    }

    return newFood;
};

/**
 * Update an existing food item in the local database
 */
export const updateFood = async (id: number, data: any) => {
    const food = await db.query.foodItems.findFirst({
        where: eq(foodItems.id, id),
    });

    if (!food) {
        throw new NotFound(`Food item with ID ${id} not found`);
    }

    const { class_name, ...updates } = data;

    if (class_name && class_name !== food.class_name) {
        const existing = await db.query.foodItems.findFirst({
            where: eq(foodItems.class_name, class_name),
        });

        if (existing) {
            throw new BadRequest("Food item name is already taken");
        }
        updates.class_name = class_name;
    }

    if (Object.keys(updates).length > 0) {
        await db.update(foodItems).set(updates).where(eq(foodItems.id, id));
    }

    const updatedFood = await db.query.foodItems.findFirst({
        where: eq(foodItems.id, id),
    });

    if (!updatedFood) {
        throw new BadRequest("Failed to retrieve updated food item");
    }

    return updatedFood;
};

/**
 * Delete a food item and clear referencing daily logs, recipe ingredients, and meal plan items
 */
export const deleteFood = async (id: number) => {
    const food = await db.query.foodItems.findFirst({
        where: eq(foodItems.id, id),
    });

    if (!food) {
        throw new NotFound(`Food item with ID ${id} not found`);
    }

    await db.transaction(async (tx) => {
        // 1. Delete dependent recipe ingredients
        await tx.delete(recipeIngredients).where(eq(recipeIngredients.foodItemId, id));

        // 2. Delete dependent meal plan items
        await tx.delete(mealPlanItems).where(eq(mealPlanItems.foodItemId, id));

        // 3. Delete daily logs referencing this food item
        await tx.delete(dailyLogs).where(eq(dailyLogs.foodItemId, id));

        // 4. Delete the food item
        await tx.delete(foodItems).where(eq(foodItems.id, id));
    });

    return { id, message: "Food item and all related records deleted successfully" };
};
