"""Editing Table of Chats

Revision ID: 9e9dadc6af3a
Revises: eb4bd3820b41
Create Date: 2026-04-01 01:07:48.117774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9dadc6af3a'
down_revision: Union[str, Sequence[str], None] = 'eb4bd3820b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
