import { aiApiRequest , apiRequest } from "../api/apiRequest.service";
import { aiBaseurl } from "../../constants/api.constants";
import { db } from "../../db/connection";
import { foodItems } from "../../models/food_items";
import { eq } from "drizzle-orm";

export const getAllFood = async (params: {
    page?:   number;
    limit?:  number;
    search?: string;
}) => {
    const query = new URLSearchParams();
    if (params.page)   query.append("page",   params.page.toString());
    if (params.limit)  query.append("limit",  params.limit.toString());
    if (params.search) query.append("search", params.search);

    const queryString = query.size ? `?${query.toString()}` : "";
    return apiRequest(`${aiBaseurl}/food/${queryString}`, "GET", {});
};

export const getFoodById = async (id: string) => {
    const response = await apiRequest(`${aiBaseurl}/food/${id}`, "GET", {});
    return response;
};



//! Created by Antigravity: Service to create or get a custom food item generated by the AI
export const createOrGetCustomFood = async (data: {
    name: string;
    calories: number;
    protein: number;
    carbs: number;
    fats: number;
}) => {
    // Check if the food already exists to avoid unique constraint errors
    const existingFood = await db.query.foodItems.findFirst({
        where: eq(foodItems.class_name, data.name)
    });

    if (existingFood) {
        return existingFood;
    }

    // Insert new custom food. We store the raw macros in the per_100g fields
    // so that logging it with quantity=100 will yield the exact macro amounts.
    await db.insert(foodItems).values({
        class_name: data.name,
        cals_per_100g: data.calories,
        protein_per_100g: data.protein,
        carbs_per_100g: data.carbs,
        fats_per_100g: data.fats,
        source: 'UserCreated',
        isVerified: false,
    });

    const newFood = await db.query.foodItems.findFirst({
        where: eq(foodItems.class_name, data.name)
    });

    return newFood;
};
